packages:
- name: "bind"
  release: "ThinXR_7.3.15"
  version: "1.0.1"
  sources:
    - name: bind
      file: bind-configs/bind.tar
  config-dir:
    - name: bind-configs
      dir: bind-configs/config
